FROM n8nio/n8n

ENV NODE_ENV=production
ENV N8N_PORT=5678
ENV WEBHOOK_URL=https://${RAILWAY_STATIC_URL}
ENV N8N_PROTOCOL=https
ENV N8N_HOST=${RAILWAY_STATIC_URL}
ENV N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

EXPOSE 5678