version: '3'
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - DB_POSTGRESDB_URL=${DB_POSTGRESDB_URL}
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
