version: '3'
services:
  n8n:
    image: n8nio/n8n:1.102.3
    restart: always
    ports:
      - "5678:5678"
    environment:
      - NODE_ENV=production
      - N8N_PORT=5678
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - DB_TYPE=${DB_TYPE}
      - DB_SQLITE_DISABLED=${DB_SQLITE_DISABLED}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_PROTOCOL=https
      - N8N_HOST=${RAILWAY_STATIC_URL}
      - WEBHOOK_URL=https://${RAILWAY_STATIC_URL}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=${N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS}
    volumes:
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:
